### ISSUE TITLE
Checklist for project migration

### ISSUE THREAD

**Issue by ethteck** [decompals/frogress#38]
Since we'll be moving from frogress to the decomp.dev storage system, let's track which projects we need to move off of frogress and onto that. Once this list is complete, we can ingest all frogress data and then shut down frogress. 

- [x] [prime](https://progress.deco.mp/admin/frog_api/project/1/change/)
- [x] [smg](https://progress.deco.mp/admin/frog_api/project/43/change/)
- [x] [key](https://progress.deco.mp/admin/frog_api/project/42/change/)
- [x] [pikmin](https://progress.deco.mp/admin/frog_api/project/40/change/)
- [x] [pokeorre](https://progress.deco.mp/admin/frog_api/project/39/change/)
- [x] [oot-gc](https://progress.deco.mp/admin/frog_api/project/37/change/)
- [x] [mkdd](https://progress.deco.mp/admin/frog_api/project/31/change/)
- [x] [bfbb](https://progress.deco.mp/admin/frog_api/project/30/change/)
- [x] [ss](https://progress.deco.mp/admin/frog_api/project/29/change/)
- [x] [marioparty4](https://progress.deco.mp/admin/frog_api/project/28/change/)
- [x] [rb3](https://progress.deco.mp/admin/frog_api/project/25/change/)
- [x] [animalcrossing](https://progress.deco.mp/admin/frog_api/project/22/change/)
- [x] [tww](https://progress.deco.mp/admin/frog_api/project/21/change/)
- [x] [twilightprincess](https://progress.deco.mp/admin/frog_api/project/17/change/)
- [x] [melee](https://progress.deco.mp/admin/frog_api/project/11/change/)
- [x] [xenoblade](https://progress.deco.mp/admin/frog_api/project/6/change/)
- [x] [echoes](https://progress.deco.mp/admin/frog_api/project/4/change/)
- [x] [pikmin2](https://progress.deco.mp/admin/frog_api/project/3/change/)
- [x] [aliceinwonderland](https://progress.deco.mp/admin/frog_api/project/35/change/)
- [x] [slycooper1](https://progress.deco.mp/admin/frog_api/project/32/change/)
- [x] [ty](https://progress.deco.mp/admin/frog_api/project/23/change/)
- [x] [oot-vc](https://progress.deco.mp/admin/frog_api/project/38/change/)
- [x] [drmario64](https://progress.deco.mp/admin/frog_api/project/2/change/)
- [x] [mkw](https://progress.deco.mp/admin/frog_api/project/24/change/)
- [x] [puzzleleague64](https://progress.deco.mp/admin/frog_api/project/7/change/)
- [x] [psyq](https://progress.deco.mp/admin/frog_api/project/26/change/)
- [ ] [pokemonsnap](https://progress.deco.mp/admin/frog_api/project/27/change/)
- [ ] [tooie](https://progress.deco.mp/admin/frog_api/project/41/change/)
- [ ] [sotn](https://progress.deco.mp/admin/frog_api/project/5/change/)
- [ ] [chameleontwist](https://progress.deco.mp/admin/frog_api/project/10/change/)
- [ ] [animalforest](https://progress.deco.mp/admin/frog_api/project/8/change/)
- [ ] [fireemblem7j](https://progress.deco.mp/admin/frog_api/project/16/change/)
- [ ] [dukezh](https://progress.deco.mp/admin/frog_api/project/15/change/)
- [ ] [fireemblem6](https://progress.deco.mp/admin/frog_api/project/13/change/)
- [ ] [fireemblem8](https://progress.deco.mp/admin/frog_api/project/12/change/)
- [ ] [yoshisstory](https://progress.deco.mp/admin/frog_api/project/19/change/)
- [ ] [sotc](https://progress.deco.mp/admin/frog_api/project/34/change/)
